spring.application.name=duetracker
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5434/duestracker
spring.datasource.username=dues
spring.datasource.password=dues

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true